### ISSUE TITLE
Request for file removal: acumin-bold.otf

### ISSUE THREAD

**Issue by miguelsousa** [twentytwoo/jekyll-messenger#3]
When using http://www.getthefont.com/, I found your font file [acumin-bold.otf](http://github.com/twentytwoo/jekyll-messenger/blob/52cfb77cd304fc574f46d19d671b01912d78eef6/css/acumin-bold.otf), uploaded in this repository. I believe that this file was uploaded here by mistake, because its license does not allow distribution through a public website.

I would like to kindly ask you to remove this font file from the repository.

Kind regards,

**Comment by twentytwoo** [comment]
done ;0
